[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hilbox"
version = "0.1.0"
description = "A simple RESTâ€based HIL box client"
authors = [{name="edward", email="edwardfeiwang@gmail.com"}]
dependencies = ["requests>=2.0"]
